{
 "title": "CPU",
 "tags": [
  "nuodb",
  "cpu"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "group", "label": "Grouping", "query": "host,db,nodetype,pid" },
   {
    "name": "database",
    "label": "Database",
    "query": "SHOW TAG VALUES FROM \"Milliseconds\" WITH KEY = \"db\""
   },
   {
    "name": "host",
    "label": "Host",
    "query": "SHOW TAG VALUES FROM \"Milliseconds\" WITH KEY = \"host\" WHERE  \"db\" =~ /^$database$/"
   }
  ]
 },
 "panels": [
  { "title": "CPU Averages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "User",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PercentUserTime",
     "query": "SELECT last(a) FROM (SELECT mean(\"norm\") as a FROM \"PercentUserTime\" WHERE \"nodetype\" = 'Transaction' AND \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/ AND  $timeFilter GROUP BY time(1m) fill(0))",
     "select": [
      [
       { "params": [ "norm" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" }
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PercentSystemTime",
     "query": "SELECT last(a) FROM (SELECT mean(\"norm\") as a FROM \"PercentSystemTime\" WHERE \"nodetype\" = 'Transaction' AND  \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/ AND  $timeFilter GROUP BY time(1m) fill(0))",
     "select": [
      [
       { "params": [ "norm" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" }
     ]
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PercentCpuTime",
     "query": "SELECT last(a) FROM (SELECT mean(\"norm\") as a FROM \"PercentCpuTime\" WHERE \"nodetype\" = 'Transaction' AND  \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/ AND  $timeFilter GROUP BY time(1m) fill(0))",
     "select": [
      [
       { "params": [ "norm" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" }
     ]
    }
   ]
  },
  {
   "title": "# TE",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "Milliseconds",
     "query": "SELECT COUNT(min) FROM (SELECT MIN(\"raw\") FROM \"Milliseconds\" WHERE \"nodetype\" = 'Transaction' AND  \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/ AND  $timeFilter GROUP BY \"host\")",
     "select": [
      [
       { "params": [ "raw" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" }
     ]
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 3, "w": 2, "x": 8, "y": 1 } },
  {
   "title": "# Host",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "Milliseconds",
     "query": "select count(last) from ( select last(raw),time from \"NumberCores\" where  \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/ AND  $timeFilter group by \"host\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "# Cores",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(last) from ( select last(raw),time from \"NumberCores\" where  \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/ AND  $timeFilter group by \"host\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 3, "w": 2, "x": 14, "y": 1 } },
  {
   "title": "# SM",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Milliseconds",
     "query": "SELECT COUNT(min) FROM (SELECT MIN(\"raw\") FROM \"Milliseconds\" WHERE \"nodetype\" = 'Storage' AND  \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/ AND  $timeFilter GROUP BY \"host\")",
     "select": [
      [
       { "params": [ "raw" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    }
   ]
  },
  {
   "title": "User",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PercentUserTime",
     "query": "SELECT last(a) FROM (SELECT mean(\"norm\") as a FROM \"PercentUserTime\" WHERE \"nodetype\" = 'Storage' AND   \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/ AND  $timeFilter GROUP BY time(1m) fill(0))",
     "select": [
      [
       { "params": [ "norm" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PercentSystemTime",
     "query": "SELECT last(a) FROM (SELECT mean(\"norm\") as a FROM \"PercentSystemTime\" WHERE \"nodetype\" = 'Storage' AND  \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/ AND   $timeFilter GROUP BY time(1m) fill(0))",
     "select": [
      [
       { "params": [ "norm" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PercentCpuTime",
     "query": "SELECT last(a) FROM (SELECT mean(\"norm\") as a FROM \"PercentCpuTime\" WHERE \"nodetype\" = 'Storage' AND  \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/ AND  $timeFilter GROUP BY time(1m) fill(0))",
     "select": [
      [
       { "params": [ "norm" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    }
   ]
  },
  { "title": "CPU measured by cores", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Average CPU Usage measured by # cores",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "TE - System",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PercentSystemTime",
     "query": " SELECT MEAN(A) FROM (SELECT mean(ncores) AS A FROM \"PercentSystemTime\" WHERE nodetype = 'Transaction' AND  \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/ AND  $timeFilter GROUP BY time($__interval), host, pid fill(none)) WHERE  $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "ncores" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    },
    {
     "alias": "TE - User",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PercentSystemTime",
     "query": " SELECT MEAN(A) FROM (SELECT mean(ncores) AS A FROM \"PercentUserTime\" WHERE nodetype = 'Transaction' AND  \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/ AND   $timeFilter GROUP BY time($__interval), host, pid fill(none)) WHERE  $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "ncores" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    },
    {
     "alias": "TE - Total",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PercentSystemTime",
     "query": " SELECT MEAN(A) FROM (SELECT mean(ncores) AS A FROM \"PercentCpuTime\" WHERE nodetype = 'Transaction' AND  \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/ AND  $timeFilter GROUP BY time($__interval), host, pid fill(none)) WHERE  $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "ncores" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    },
    {
     "alias": "SM - System",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PercentSystemTime",
     "query": " SELECT MEAN(A) FROM (SELECT mean(ncores) AS A FROM \"PercentSystemTime\" WHERE nodetype = 'Storage' AND  \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/ AND  $timeFilter GROUP BY time($__interval), host, pid fill(none)) WHERE  $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "ncores" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    },
    {
     "alias": "SM - User",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PercentSystemTime",
     "query": " SELECT MEAN(A) FROM (SELECT mean(ncores) AS A FROM \"PercentUserTime\" WHERE nodetype = 'Storage' AND  \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/ AND  $timeFilter GROUP BY time($__interval), host, pid fill(none)) WHERE  $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "ncores" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    },
    {
     "alias": "SM - Total",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PercentSystemTime",
     "query": " SELECT MEAN(A) FROM (SELECT mean(ncores) AS A FROM \"PercentCpuTime\" WHERE nodetype = 'Storage' AND  \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/ AND  $timeFilter GROUP BY time($__interval), host, pid fill(none)) WHERE  $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "ncores" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    }
   ]
  },
  {
   "title": "Total CPU Usage measured by # cores",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "TE - System",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PercentSystemTime",
     "query": " SELECT SUM(A) FROM (SELECT mean(ncores) AS A FROM \"PercentSystemTime\" WHERE nodetype = 'Transaction' AND  \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/ AND  $timeFilter GROUP BY time($__interval), host, pid fill(none)) WHERE  $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "ncores" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    },
    {
     "alias": "TE - User",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PercentSystemTime",
     "query": " SELECT SUM(A) FROM (SELECT mean(ncores) AS A FROM \"PercentUserTime\" WHERE nodetype = 'Transaction' AND  \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/ AND  $timeFilter GROUP BY time($__interval), host, pid fill(none)) WHERE  $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "ncores" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    },
    {
     "alias": "TE - Total",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PercentSystemTime",
     "query": " SELECT SUM(A) FROM (SELECT mean(ncores) AS A FROM \"PercentCpuTime\" WHERE nodetype = 'Transaction' AND  \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/ AND  $timeFilter GROUP BY time($__interval), host, pid fill(none)) WHERE  $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "ncores" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    },
    {
     "alias": "SM - System",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PercentSystemTime",
     "query": " SELECT SUM(A) FROM (SELECT mean(ncores) AS A FROM \"PercentSystemTime\" WHERE nodetype = 'Storage' AND  \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/ AND  $timeFilter GROUP BY time($__interval), host, pid fill(none)) WHERE  $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "ncores" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    },
    {
     "alias": "SM - User",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PercentSystemTime",
     "query": " SELECT SUM(A) FROM (SELECT mean(ncores) AS A FROM \"PercentUserTime\" WHERE nodetype = 'Storage' AND  \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/ AND  $timeFilter GROUP BY time($__interval), host, pid fill(none)) WHERE  $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "ncores" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    },
    {
     "alias": "SM - Total",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PercentSystemTime",
     "query": " SELECT SUM(A) FROM (SELECT mean(ncores) AS A FROM \"PercentCpuTime\" WHERE nodetype = 'Storage' AND  \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/ AND  $timeFilter GROUP BY time($__interval), host, pid fill(none)) WHERE  $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "ncores" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    }
   ]
  },
  { "title": "Avg CPU by $group", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "TE CPU % by $group",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "TE System - $tag_$group",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "$group" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PercentSystemTime",
     "select": [
      [
       { "params": [ "norm" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    },
    {
     "alias": "TE User   - $tag_$group",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "$group" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PercentUserTime",
     "select": [
      [
       { "params": [ "norm" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    },
    {
     "alias": "TE Total   - $tag_$group",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "$group" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PercentCpuTime",
     "select": [
      [
       { "params": [ "norm" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "SM CPU % by $group",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "SM System - $tag_$group",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "$group" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PercentSystemTime",
     "select": [
      [
       { "params": [ "norm" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    },
    {
     "alias": "SM User   - $tag_$group",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "$group" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PercentUserTime",
     "select": [
      [
       { "params": [ "norm" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    },
    {
     "alias": "SM Total   - $tag_$group",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "$group" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PercentCpuTime",
     "select": [
      [
       { "params": [ "norm" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    }
   ]
  },
  {
   "title": "$host CPU by $group",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "$host - $group breakdown",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 17 },
     "repeat": "host",
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "System - $tag_$group",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "$group" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "PercentSystemTime",
       "query": "SELECT sum(\"N\") FROM (SELECT mean(\"norm\") AS \"N\" FROM \"PercentSystemTime\" WHERE \"host\" = '$host' AND $timeFilter GROUP BY time($interval),  \"pid\", \"$group\" fill(0)) WHERE $timeFilter GROUP BY time($interval), \"$group\"",
       "select": [
        [
         { "params": [ "norm" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "$host" }
       ]
      },
      {
       "alias": "User - $tag_$group",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "$group" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "PercentUserTime",
       "query": "SELECT sum(\"N\") FROM (SELECT mean(\"norm\") AS \"N\" FROM \"PercentUserTime\" WHERE \"host\" = '$host' AND $timeFilter GROUP BY time($interval),  \"pid\", \"$group\" fill(0)) WHERE $timeFilter GROUP BY time($interval), \"$group\"",
       "select": [
        [
         { "params": [ "norm" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "$host" }
       ]
      },
      {
       "alias": "Total - $tag_$group",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "$group" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "PercentCpuTime",
       "query": "SELECT sum(\"N\") FROM (SELECT mean(\"norm\") AS \"N\" FROM \"PercentCpuTime\" WHERE \"host\" = '$host' AND $timeFilter GROUP BY time($interval),  \"pid\", \"$group\" fill(0)) WHERE $timeFilter GROUP BY time($interval), \"$group\"",
       "select": [
        [
         { "params": [ "norm" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "$host" }
       ]
      }
     ]
    }
   ]
  }
 ]
}