{
 "title": "Memory",
 "tags": [
  "nuodb",
  "memory"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "database",
    "label": "Database",
    "query": "SHOW TAG VALUES FROM \"Milliseconds\" WITH KEY = \"db\""
   },
   {
    "name": "host",
    "label": "Host",
    "query": "SHOW TAG VALUES FROM \"Milliseconds\" WITH KEY = \"host\" WHERE \"db\" =~ /^$database$/ "
   }
  ]
 },
 "panels": [
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "TE - $tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HeapAllocated",
     "query": "SELECT SUM(M) FROM (SELECT mean(\"raw\") AS M FROM \"HeapAllocated\" WHERE \"host\" =~ /^$host$/ AND (\"nodetype\" = 'Transaction' AND \"db\" =~ /^$database$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"pid\" fill(null)) WHERE $timeFilter GROUP BY time($__interval), \"host\"",
     "select": [
      [
       { "params": [ "raw" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "SM - $tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(M) FROM (SELECT mean(\"raw\") AS M FROM \"HeapAllocated\" WHERE \"host\" =~ /^$host$/ AND  \"db\" =~ /^$database$/ AND (\"nodetype\" = 'Storage') AND $timeFilter GROUP BY time($__interval), \"host\", \"pid\" fill(null)) WHERE $timeFilter GROUP BY time($__interval), \"host\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Objects",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "TE - $tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(M) FROM (SELECT mean(\"raw\") AS M FROM \"Objects\" WHERE \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/ AND (\"nodetype\" = 'Transaction') AND $timeFilter GROUP BY time($__interval), \"host\", \"pid\" fill(null)) WHERE $timeFilter GROUP BY time($__interval), \"host\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "SM - $tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(M) FROM (SELECT mean(\"raw\") AS M FROM \"Objects\" WHERE \"host\" =~ /$host$/ AND \"db\" =~ /^$database$/ AND (\"nodetype\" = 'Storage') AND $timeFilter GROUP BY time($__interval), \"host\", \"pid\" fill(null)) WHERE $timeFilter GROUP BY time($__interval), \"host\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Created / Second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "TE - $tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ObjectsCreated",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    }
   ]
  },
  {
   "title": "Dropped",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "TE - $tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ObjectsDropped",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    },
    {
     "alias": "SM - $tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ObjectsDropped",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    }
   ]
  },
  {
   "title": "Loaded / Reloaded",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "loaded - $tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ObjectsLoaded",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    },
    {
     "alias": "reloaded - $tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ObjectsReloaded",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       },
       { "params": [ "*-1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    }
   ]
  },
  {
   "title": "Purged",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "SM - $tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ObjectsPurged",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    }
   ]
  },
  {
   "title": "Imported",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ObjectsImported",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    },
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ObjectsImported",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    }
   ]
  },
  {
   "title": "Exported",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ObjectsExported",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    },
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ObjectsExported",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    }
   ]
  }
 ]
}