apiVersion: "v1"
name: insights
version: 1.1.0
description: NuoDB Insights - Visual Monitoring
keywords:
- monitoring
- nuodb
- influxdb
- grafana
home: https://github.com/nuodb/nuodb-insights/stable/insights
maintainers:
- name: NuoDB
  email: support@nuodb.com
engine: gotpl
icon: https://www.nuodb.com/sites/all/themes/nuodb/logo.svg
appVersion: 4.0.0
tillerVersion: ">=2.9"

