dependencies:
- name: grafana
  condition: grafana.enabled
  tags:
    - backend
  repository: https://grafana.github.io/helm-charts
  version: 6.1.2
- name: influxdb
  condition: influxdb.enabled
  tags:
    - backend
  repository: https://helm.influxdata.com/
  version: 4.8.9
