{
 "title": "CPU",
 "tags": [
  "nuodb",
  "cpu"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "10s,30s,1m,5m,10m,15m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "group", "label": "Grouping", "query": "host,db,nodetype,startid" },
   {
    "name": "database",
    "label": "Database",
    "query": "select distinct(\"db\") from (select first(raw) from \"Milliseconds\" where $timeFilter GROUP BY \"db\")"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "select distinct(\"host\") from (select first(raw) from \"Milliseconds\" where $timeFilter AND db =~ /$database$/ GROUP BY \"host\")"
   }
  ]
 },
 "panels": [
  { "title": "CPU Averages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "User",
   "type": "singlestat",
   "description": "Average User CPU time for TEs in the most recent 1m interval of current time window,  filters Database and Host are applied.",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PercentSystemTime",
     "query": "SELECT mean(\"norm\") as a FROM \"PercentUserTime\" WHERE \"nodetype\" = 'Transaction' AND \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/ AND  time > ${__to}ms - 1m AND time <= ${__to}ms",
     "select": [
      [
       { "params": [ "norm" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" }
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "singlestat",
   "description": "Average System CPU time for TEs in the most recent 1m interval of current time window,  filters Database and Host are applied.",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PercentSystemTime",
     "query": "SELECT mean(\"norm\") as a FROM \"PercentSystemTime\" WHERE \"nodetype\" = 'Transaction' AND \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/ AND  time > ${__to}ms - 1m AND time <= ${__to}ms",
     "select": [
      [
       { "params": [ "norm" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" }
     ]
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "description": "Average Total CPU time for TEs in the most recent 1m interval of current time window,  filters Database and Host are applied.",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PercentCpuTime",
     "query": "SELECT mean(\"norm\") as a FROM \"PercentCpuTime\" WHERE \"nodetype\" = 'Transaction' AND \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/ AND  time > ${__to}ms - 1m AND time <= ${__to}ms",
     "select": [
      [
       { "params": [ "norm" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" }
     ]
    }
   ]
  },
  {
   "title": "# TE",
   "type": "singlestat",
   "description": "Number of TEs seen in the last minute.    Filters for Database and Host are considered.",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "Milliseconds",
     "query": "SELECT COUNT(min) FROM (SELECT MIN(\"raw\") FROM \"Milliseconds\" WHERE \"nodetype\" = 'Transaction' AND  \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/ AND  $timeFilter GROUP BY \"host\")",
     "select": [
      [
       { "params": [ "raw" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" }
     ]
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 3, "w": 2, "x": 8, "y": 1 } },
  {
   "title": "# Host",
   "type": "singlestat",
   "description": "Number of host running either an SM or TE within the most recent one minute interval for the current time window.   Filters Database and Host are applied.",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(last) FROM (SELECT last(\"value\") FROM \"Milliseconds\" WHERE  \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/ AND time > ${__to}ms - 1m AND time <= ${__to}ms group by \"host\" fill(null))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "# Cores",
   "type": "singlestat",
   "description": "Total number of cores detected in the most recent one minute interval of the current time window associated with a host running either an SM or TE.   Filters Database and Host are applied.",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(last) FROM (SELECT last(\"raw\") FROM \"NumberCores\" WHERE  \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/ AND time > ${__to}ms - 1m AND time <= ${__to}ms group by \"host\" fill(null))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 3, "w": 2, "x": 14, "y": 1 } },
  {
   "title": "# SM",
   "type": "singlestat",
   "description": "Number of SMs seen in the last minute.    Filters for Database and Host are considered.",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Milliseconds",
     "query": "SELECT COUNT(min) FROM (SELECT MIN(\"raw\") FROM \"Milliseconds\" WHERE \"nodetype\" = 'Storage' AND  \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/ AND  time > ${__to}ms - 1m AND time <= ${__to}ms  GROUP BY \"startid\")",
     "select": [
      [
       { "params": [ "raw" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    }
   ]
  },
  {
   "title": "User",
   "type": "singlestat",
   "description": "Average User CPU time for SMs in the most recent 1m interval of current time window,  filters Database and Host are applied.",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PercentUserTime",
     "query": "SELECT mean(\"norm\") as a FROM \"PercentUserTime\" WHERE \"nodetype\" = 'Storage' AND \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/ AND  time > ${__to}ms - 1m AND time <= ${__to}ms",
     "select": [
      [
       { "params": [ "norm" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "singlestat",
   "description": "Average System CPU time for SMs in the most recent 1m interval of current time window,  filters Database and Host are applied.",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PercentSystemTime",
     "query": "SELECT mean(\"norm\") as a FROM \"PercentSystemTime\" WHERE \"nodetype\" = 'Storage' AND \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/ AND  time > ${__to}ms - 1m AND time <= ${__to}ms",
     "select": [
      [
       { "params": [ "norm" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "description": "Average Total CPU time for SMs in the most recent 1m interval of current time window,  filters Database and Host are applied.",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PercentCpuTime",
     "query": "SELECT mean(\"norm\") as a FROM \"PercentCpuTime\" WHERE \"nodetype\" = 'Storage' AND \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/ AND  time > ${__to}ms - 1m AND time <= ${__to}ms",
     "select": [
      [
       { "params": [ "norm" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    }
   ]
  },
  { "title": "CPU measured by cores", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Average CPU Usage measured by # cores",
   "type": "graph",
   "description": "Average CPU time as measured by number of cores for each engine type,  filters for Database and Host limit which processes to consider.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "TE - System",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PercentSystemTime",
     "query": "SELECT mean(ncores) AS A FROM \"PercentSystemTime\" WHERE nodetype = 'Transaction' AND  \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/ AND  $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "ncores" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    },
    {
     "alias": "TE - User",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PercentSystemTime",
     "query": "SELECT mean(ncores) AS A FROM \"PercentUserTime\" WHERE nodetype = 'Transaction' AND  \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/ AND  $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "ncores" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    },
    {
     "alias": "TE - Total",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PercentSystemTime",
     "query": "SELECT mean(ncores) AS A FROM \"PercentCpuTime\" WHERE nodetype = 'Transaction' AND  \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/ AND  $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "ncores" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    },
    {
     "alias": "SM - System",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PercentSystemTime",
     "query": "SELECT mean(ncores) AS A FROM \"PercentSystemTime\" WHERE nodetype = 'Storage' AND  \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/ AND  $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "ncores" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    },
    {
     "alias": "SM - User",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PercentSystemTime",
     "query": "SELECT mean(ncores) AS A FROM \"PercentUserTime\" WHERE nodetype = 'Storage' AND  \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/ AND  $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "ncores" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    },
    {
     "alias": "SM - Total",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PercentSystemTime",
     "query": "SELECT mean(ncores) AS A FROM \"PercentCpuTime\" WHERE nodetype = 'Storage' AND  \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/ AND  $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "ncores" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    }
   ]
  },
  {
   "title": "Total CPU Usage measured by # cores",
   "type": "graph",
   "description": "Total CPU time as measured by number of cores for each engine type,  filters for Database and Host limit which processes to consider.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "TE - System",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PercentSystemTime",
     "query": " SELECT SUM(A) FROM (SELECT mean(ncores) AS A FROM \"PercentSystemTime\" WHERE nodetype = 'Transaction' AND  \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/ AND  $timeFilter GROUP BY time($__interval), startid fill(none)) WHERE  $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "ncores" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    },
    {
     "alias": "TE - User",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PercentSystemTime",
     "query": " SELECT SUM(A) FROM (SELECT mean(ncores) AS A FROM \"PercentUserTime\" WHERE nodetype = 'Transaction' AND  \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/ AND  $timeFilter GROUP BY time($__interval), startid fill(none)) WHERE  $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "ncores" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    },
    {
     "alias": "TE - Total",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PercentSystemTime",
     "query": " SELECT SUM(A) FROM (SELECT mean(ncores) AS A FROM \"PercentCpuTime\" WHERE nodetype = 'Transaction' AND  \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/ AND  $timeFilter GROUP BY time($__interval), startid fill(none)) WHERE  $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "ncores" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    },
    {
     "alias": "SM - System",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PercentSystemTime",
     "query": " SELECT SUM(A) FROM (SELECT mean(ncores) AS A FROM \"PercentSystemTime\" WHERE nodetype = 'Storage' AND  \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/ AND  $timeFilter GROUP BY time($__interval), startid fill(none)) WHERE  $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "ncores" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    },
    {
     "alias": "SM - User",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PercentSystemTime",
     "query": " SELECT SUM(A) FROM (SELECT mean(ncores) AS A FROM \"PercentUserTime\" WHERE nodetype = 'Storage' AND  \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/ AND  $timeFilter GROUP BY time($__interval), startid fill(none)) WHERE  $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "ncores" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    },
    {
     "alias": "SM - Total",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PercentSystemTime",
     "query": " SELECT SUM(A) FROM (SELECT mean(ncores) AS A FROM \"PercentCpuTime\" WHERE nodetype = 'Storage' AND  \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/ AND  $timeFilter GROUP BY time($__interval), startid fill(none)) WHERE  $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "ncores" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    }
   ]
  },
  { "title": "Avg CPU by $group", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "TE CPU % by $group",
   "type": "graph",
   "description": "Average CPU usage across all TEs (each TE is given same weight independent of number of cores available for that TE),  filter criteria of Database and Host are considered,  results are grouped based upon Grouping criteria.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "TE System - $tag_$group",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "$group" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PercentSystemTime",
     "query": "SELECT mean(\"norm\") FROM \"PercentSystemTime\" WHERE (\"nodetype\" = 'Transaction' AND \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/) AND $timeFilter GROUP BY time($__interval), \"$group\" fill(null)",
     "select": [
      [
       { "params": [ "norm" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    },
    {
     "alias": "TE User   - $tag_$group",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "$group" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PercentUserTime",
     "select": [
      [
       { "params": [ "norm" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    },
    {
     "alias": "TE Total   - $tag_$group",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "$group" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PercentCpuTime",
     "select": [
      [
       { "params": [ "norm" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "SM CPU % by $group",
   "type": "graph",
   "description": "Average CPU usage across all SMs (each SM is given same weight independent of number of cores available for that SM),  filter criteria of Database and Host are considered,  results are grouped based upon Grouping criteria.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "SM System - $tag_$group",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "$group" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PercentSystemTime",
     "select": [
      [
       { "params": [ "norm" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    },
    {
     "alias": "SM User   - $tag_$group",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "$group" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PercentUserTime",
     "select": [
      [
       { "params": [ "norm" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    },
    {
     "alias": "SM Total   - $tag_$group",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "$group" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PercentCpuTime",
     "select": [
      [
       { "params": [ "norm" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    }
   ]
  },
  { "title": "per host CPU by $group", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "$host - $group breakdown",
   "type": "graph",
   "description": "CPU usage by $group for $host host",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 17 },
   "repeat": "host",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "System - $tag_$group",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "$group" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PercentSystemTime",
     "query": "SELECT sum(\"N\") FROM (SELECT mean(\"norm\") AS \"N\" FROM \"PercentSystemTime\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval),  \"startid\", \"$group\" fill(null)) WHERE $timeFilter GROUP BY time($interval), \"$group\"",
     "select": [
      [
       { "params": [ "norm" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "$host" }
     ]
    },
    {
     "alias": "User - $tag_$group",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "$group" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PercentUserTime",
     "query": "SELECT sum(\"N\") FROM (SELECT mean(\"norm\") AS \"N\" FROM \"PercentUserTime\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval),  \"startid\", \"$group\" fill(null)) WHERE $timeFilter GROUP BY time($interval), \"$group\"",
     "select": [
      [
       { "params": [ "norm" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "$host" }
     ]
    },
    {
     "alias": "Total - $tag_$group",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "$group" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PercentCpuTime",
     "query": "SELECT sum(\"N\") FROM (SELECT mean(\"norm\") AS \"N\" FROM \"PercentCpuTime\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval),  \"startid\", \"$group\" fill(null)) WHERE $timeFilter GROUP BY time($interval), \"$group\"",
     "select": [
      [
       { "params": [ "norm" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "$host" }
     ]
    }
   ]
  },
  {
   "title": "$host - $group breakdown",
   "type": "graph",
   "description": "CPU usage by $group for $host host",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "System - $tag_$group",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "$group" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PercentSystemTime",
     "query": "SELECT sum(\"N\") FROM (SELECT mean(\"norm\") AS \"N\" FROM \"PercentSystemTime\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval),  \"startid\", \"$group\" fill(null)) WHERE $timeFilter GROUP BY time($interval), \"$group\"",
     "select": [
      [
       { "params": [ "norm" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "$host" }
     ]
    },
    {
     "alias": "User - $tag_$group",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "$group" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PercentUserTime",
     "query": "SELECT sum(\"N\") FROM (SELECT mean(\"norm\") AS \"N\" FROM \"PercentUserTime\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval),  \"startid\", \"$group\" fill(null)) WHERE $timeFilter GROUP BY time($interval), \"$group\"",
     "select": [
      [
       { "params": [ "norm" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "$host" }
     ]
    },
    {
     "alias": "Total - $tag_$group",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "$group" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PercentCpuTime",
     "query": "SELECT sum(\"N\") FROM (SELECT mean(\"norm\") AS \"N\" FROM \"PercentCpuTime\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval),  \"startid\", \"$group\" fill(null)) WHERE $timeFilter GROUP BY time($interval), \"$group\"",
     "select": [
      [
       { "params": [ "norm" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "$host" }
     ]
    }
   ]
  }
 ]
}