{
 "title": "Memory",
 "tags": [
  "nuodb",
  "memory"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "10s,30s,1m,5m,10m,15m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "database",
    "label": "Database",
    "query": "select distinct(\"db\") from (select first(raw) from \"Milliseconds\" where $timeFilter AND domain =~ /^$domain$/ GROUP BY \"db\")\n"
   },
   {
    "name": "domain",
    "label": "Domain",
    "query": "show tag values from \"Milliseconds\" with key in (\"domain\")  where \"domain\" = '${__user.login}'"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "select distinct(\"host\") from (select first(raw) from \"Milliseconds\" where $timeFilter AND domain =~ /^$domain$/ AND db =~ /^$database$/ GROUP BY \"host\")"
   }
  ]
 },
 "panels": [
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "The average amount of heap allocated memory  for each engine.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "TE(host: $tag_host, db: $tag_db, nodeid: $tag_nodeid, startid: $tag_startid)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "nodeid" ], "type": "tag" },
      { "params": [ "startid" ], "type": "tag" },
      { "params": [ "db" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HeapAllocated",
     "select": [
      [
       { "params": [ "raw" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    },
    {
     "alias": "SM(host: $tag_host, db: $tag_db, nodeid: $tag_nodeid, startid: $tag_startid)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "db" ], "type": "tag" },
      { "params": [ "nodeid" ], "type": "tag" },
      { "params": [ "startid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HeapAllocated",
     "select": [
      [
       { "params": [ "raw" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    }
   ]
  },
  {
   "title": "Objects",
   "type": "graph",
   "description": "The average number of objects in memory for each engine.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "TE(host: $tag_host, db: $tag_db, nodeid: $tag_nodeid, startid: $tag_startid)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "db" ], "type": "tag" },
      { "params": [ "nodeid" ], "type": "tag" },
      { "params": [ "startid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Objects",
     "select": [
      [
       { "params": [ "raw" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    },
    {
     "alias": "SM(host: $tag_host, db: $tag_db, nodeid: $tag_nodeid, startid: $tag_startid)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "db" ], "type": "tag" },
      { "params": [ "nodeid" ], "type": "tag" },
      { "params": [ "startid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Objects",
     "select": [
      [
       { "params": [ "raw" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    }
   ]
  },
  {
   "title": "Created",
   "type": "graph",
   "description": "Average number of objects created per second by each engine within the interval.  Only TEs create new objects.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "TE(host: $tag_host, db: $tag_db, nodeid: $tag_nodeid, startid: $tag_startid)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "db" ], "type": "tag" },
      { "params": [ "nodeid" ], "type": "tag" },
      { "params": [ "startid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ObjectsCreated",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    },
    {
     "alias": "SM(host: $tag_host, db: $tag_db, nodeid: $tag_nodeid, startid: $tag_startid)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "db" ], "type": "tag" },
      { "params": [ "nodeid" ], "type": "tag" },
      { "params": [ "startid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ObjectsCreated",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    }
   ]
  },
  {
   "title": "Dropped",
   "type": "graph",
   "description": "Average number of objects dropped per second by each engine within the interval.   Objects are dropped by garbage collector to make room for new objects to be created or imported.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "TE(host: $tag_host, db: $tag_db, nodeid: $tag_nodeid, startid: $tag_startid)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "db" ], "type": "tag" },
      { "params": [ "startid" ], "type": "tag" },
      { "params": [ "nodeid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ObjectsDropped",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    },
    {
     "alias": "SM(host: $tag_host, db: $tag_db, nodeid: $tag_nodeid, startid: $tag_startid)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "db" ], "type": "tag" },
      { "params": [ "nodeid" ], "type": "tag" },
      { "params": [ "startid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ObjectsDropped",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    }
   ]
  },
  {
   "title": "Loaded / Reloaded",
   "type": "graph",
   "description": "Above the x-axis is the average number of objects per second loaded into each SM.  Below the x-axis list the number of objects reloaded into each SM.  An object is reloaded if it was purged from SM memory and a TE already has that object in memory.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "SM( host: $tag_host, db: $tag_db, nodeid: $tag_nodeid, startid: $tag_startid):loaded",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "db" ], "type": "tag" },
      { "params": [ "nodeid" ], "type": "tag" },
      { "params": [ "startid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ObjectsLoaded",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    },
    {
     "alias": "SM( host: $tag_host, db: $tag_db, nodeid: $tag_nodeid, startid: $tag_startid):reloaded",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "db" ], "type": "tag" },
      { "params": [ "nodeid" ], "type": "tag" },
      { "params": [ "startid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ObjectsReloaded",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    }
   ]
  },
  {
   "title": "Purged / Dropped Purged",
   "type": "graph",
   "description": "Average number of objects purged from each SM.  An object is purged if the garbage collector needs to free up space and an object is removed from cache but still exist in cache within a TE. Below the x-axis is a count of the number of objects dropped that were in the purged state for each SM.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "SM(host: $tag_host, db: $tag_db, nodeid: $tag_nodeid, startid: $tag_startid):purged",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"rate\") FROM \"ObjectsPurged\" WHERE (\"nodetype\" = 'Storage' AND \"host\" =~ /^$host$/ AND \"domain\" =~ /^$domain$/ AND \"db\" =~ /^$database$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"db\", \"nodeid\", \"startid\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "SM(host: $tag_host, db: $tag_db, nodeid: $tag_nodeid, startid: $tag_startid):dropped",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"rate\") FROM \"ObjectsDroppedPurged\" WHERE (\"nodetype\" = 'Storage' AND \"host\" =~ /^$host$/ AND \"domain\" =~ /^$domain$/ AND \"db\" =~ /^$database$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"db\", \"nodeid\", \"startid\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Imported",
   "type": "graph",
   "description": "Average number of objects per second imported into an engine.   Objects are imported into a TE when a TE needs an existing object that is not in its local cache.  Objects are imported into an SM when a TE creates new objects.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "TE(host: $tag_host, db: $tag_db, nodeid: $tag_nodeid, startid: $tag_startid)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "db" ], "type": "tag" },
      { "params": [ "nodeid" ], "type": "tag" },
      { "params": [ "startid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ObjectsImported",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    },
    {
     "alias": "SM(host: $tag_host, db: $tag_db, nodeid: $tag_nodeid, startid: $tag_startid)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "db" ], "type": "tag" },
      { "params": [ "nodeid" ], "type": "tag" },
      { "params": [ "startid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ObjectsImported",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    }
   ]
  },
  {
   "title": "Exported",
   "type": "graph",
   "description": "Average number of objects per second exported into an engine.   Objects are exported from a TE or SM when another engine needs an object that is not in its local cache.  A TE will export newly created objects to all SMs.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "TE(host: $tag_host, db: $tag_db, nodeid: $tag_nodeid, startid: $tag_startid)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "nodeid" ], "type": "tag" },
      { "params": [ "db" ], "type": "tag" },
      { "params": [ "startid" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ObjectsExported",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    },
    {
     "alias": "SM(host: $tag_host, db: $tag_db, nodeid: $tag_nodeid, startid: $tag_startid)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "nodeid" ], "type": "tag" },
      { "params": [ "startid" ], "type": "tag" },
      { "params": [ "db" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ObjectsExported",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    }
   ]
  }
 ]
}