{
 "title": "Thread Usage",
 "tags": [ "nuodb" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "10s,15s,30s,1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "filter", "label": "Filter" },
   { "name": "min", "label": "cpu", "query": "0,10,20,25,30,50,75,80,90,95" }
  ]
 },
 "panels": [
  {
   "title": "Threads over $min % CPU usage ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host:$tag_exe",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "threadid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nuodb_thread",
     "query": "SELECT mean(\"ttime\") FROM \"nuodb_thread\" WHERE (\"ttime\" > $min) AND $timeFilter GROUP BY time($__interval), \"threadid\", \"exe\",\"host\" fill(null)",
     "select": [
      [
       { "params": [ "ttime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ttime", "operator": "=", "value": "$min" }
     ]
    }
   ]
  },
  {
   "title": "CPU usage by thread type",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host:$tag_exe",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "threadid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nuodb_thread",
     "query": "SELECT sum(\"atime\") FROM (SELECT mean(\"ttime\") AS atime FROM \"nuodb_thread\" WHERE   (\"ttime\" > $min) AND  $timeFilter GROUP BY time($__interval), \"threadid\", \"exe\",\"host\" fill(null)) WHERE $timeFilter GROUP BY time($__interval), \"exe\", \"host\"",
     "select": [
      [
       { "params": [ "ttime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ttime", "operator": "=", "value": "$min" }
     ]
    }
   ]
  },
  {
   "title": "percentage of CPU by thread type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host:$tag_exe",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "threadid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nuodb_thread",
     "query": "SELECT sum(\"atime\") FROM (SELECT mean(\"ttime\") AS atime FROM \"nuodb_thread\" WHERE   (\"ttime\" > $min) AND  $timeFilter GROUP BY time($__interval), \"threadid\", \"exe\",\"host\" fill(null)) WHERE $timeFilter GROUP BY time($__interval), \"exe\", \"host\"",
     "select": [
      [
       { "params": [ "ttime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ttime", "operator": "=", "value": "$min" }
     ]
    }
   ]
  },
  {
   "title": "percentage of user CPU by thread type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host:$tag_exe",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "threadid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nuodb_thread",
     "query": "SELECT sum(\"atime\") FROM (SELECT mean(\"utime\") AS atime FROM \"nuodb_thread\" WHERE   (\"ttime\" > $min) AND  $timeFilter GROUP BY time($__interval), \"threadid\", \"exe\",\"host\" fill(null)) WHERE $timeFilter GROUP BY time($__interval), \"exe\", \"host\"",
     "select": [
      [
       { "params": [ "ttime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ttime", "operator": "=", "value": "$min" }
     ]
    }
   ]
  },
  {
   "title": "percentage of system CPU by thread type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host:$tag_exe",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "threadid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nuodb_thread",
     "query": "SELECT sum(\"atime\") FROM (SELECT mean(\"stime\") AS atime FROM \"nuodb_thread\" WHERE   (\"ttime\" > $min) AND  $timeFilter GROUP BY time($__interval), \"threadid\", \"exe\",\"host\" fill(null)) WHERE $timeFilter GROUP BY time($__interval), \"exe\", \"host\"",
     "select": [
      [
       { "params": [ "ttime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ttime", "operator": "=", "value": "$min" }
     ]
    }
   ]
  }
 ]
}