# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  # Check https://circleci.com/developer/orbs/orb/circleci/go for more details
  go: circleci/go@1.7.2

commands:
  nuodb_insight_command:
    steps:
      - checkout
      - go/install:
          version: "1.20"
      - run:
          name: Install Dependencies
          command: |
            BASE_COMMIT=$(git merge-base HEAD circleci-project-setup)
            MODIFIED_FILES=$(git diff --name-only "${BASE_COMMIT}")
            if ! echo "${MODIFIED_FILES}" | grep -qvE '(\.md$)'; then
              echo "Only docs were updated, stopping build process."
              circleci-agent step halt
            fi
            sudo apt-get update
            sudo apt-get install socat
            scripts/ci/install_deps.sh
          environment:
            GOTESTSUM_VERSION: "1.7.0"

      - run:
          name: Run tests
          command: |
            scripts/ci/determine_and_run_tests.sh
      - store_test_results:
          path: /tmp/test-results

jobs:
  build_n_run_docker:
    machine:
      image: ubuntu-2204:2023.04.2
    steps:
      - nuodb_insight_command
    environment:
      TEST_SUITE: docker
      TEST_RESULTS: /tmp/test-results
    resource_class: medium

  build_n_run_kub:
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - nuodb_insight_command
      - store_artifacts:
          path: ./results/
    resource_class: medium
    environment:
      TEST_SUITE: Kubernetes
      HELM_VERSION: "v3.5.2"
      MINIKUBE_VERSION: "1.25.2"
      KUBERNETES_VERSION: "1.21.3"
      NUODB_HELM_CHARTS_VERSION: "3.5.0"
      TEST_RESULTS: /tmp/test-results

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build_n_test:
    jobs:
      - build_n_run_docker
      - build_n_run_kub