#!/bin/bash

: ${NUODB_HOME:=/opt/nuodb}
. ${NUODB_HOME}/etc/nuodb_setup.sh

export NUODB_HOME
export NUODB_CFGDIR
export NUODB_RUNDIR
export NUODB_VARDIR
export NUODB_LOGDIR

BASEDIR="$(dirname "$(dirname "$(readlink -fm "$0")")")"

PYTHONPATH=${NUODB_HOME}/drivers/pynuoadmin:${NUODB_HOME}/etc/nuoca/lib \
exec ${NUODB_HOME}/etc/python/nuopython -mnuoca_cli start nuoca --collection-interval 10
