{
 "title": "NuoDB SQL Statements",
 "description": "NuoDB Summary",
 "tags": [ "overview" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "10s,30s,1m,5m,10m,15m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "database",
    "label": "Database",
    "query": "select distinct(\"db\") from (select first(raw) from \"Milliseconds\" where $timeFilter GROUP BY \"db\")\n"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "select distinct(\"host\") from (select first(raw) from \"Milliseconds\" where $timeFilter AND db =~ /$database$/ AND nodetype = 'Transaction' GROUP BY \"host\")\n"
   },
   {
    "name": "id",
    "label": "id",
    "query": "select distinct(\"id\") from (select first(numexecutes) from \"nuodb_statements\" where $timeFilter GROUP BY \"id\")"
   },
   { "name": "collection", "query": "10" }
  ]
 },
 "panels": [
  {
   "title": "Selectors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Executes",
     "type": "piechart",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_id",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "id::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nuodb_statements",
       "query": "select top(\"value\",10) as numexecutes, id from (SELECT mean(\"numexecutes\")  as value FROM \"nuodb_statements\" WHERE (\"host\"::tag =~ /^$host$/) AND $timeFilter GROUP BY \"id\"::tag fill(null))",
       "select": [
        [
         { "params": [ "numexecutes" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / 30" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Execute Time",
     "type": "piechart",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_id",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "id::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nuodb_statements",
       "query": "select top(\"value\",10) as value, id from (SELECT mean(\"exectime\")  as value FROM \"nuodb_statements\" WHERE (\"host\"::tag =~ /^$host$/) AND $timeFilter GROUP BY \"id\"::tag fill(null))",
       "select": [
        [
         { "params": [ "numexecutes" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / 30" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Compile Time",
     "type": "piechart",
     "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_id",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "id::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nuodb_statements",
       "query": "select top(\"value\",10) as value, id from (SELECT mean(\"compiletime\")  as value FROM \"nuodb_statements\" WHERE (\"host\"::tag =~ /^$host$/) AND $timeFilter GROUP BY \"id\"::tag fill(null))",
       "select": [
        [
         { "params": [ "numexecutes" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / 30" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Selects",
     "type": "piechart",
     "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_id",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "id::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nuodb_statements",
       "query": "select top(\"value\",10) as value, id from (SELECT mean(\"recordsreturned\")  as value FROM \"nuodb_statements\" WHERE (\"host\"::tag =~ /^$host$/) AND $timeFilter GROUP BY \"id\"::tag fill(null))",
       "select": [
        [
         { "params": [ "numexecutes" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / 30" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Inserts",
     "type": "piechart",
     "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_id",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "id::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nuodb_statements",
       "query": "select top(\"value\",10) as value, id from (SELECT mean(\"inserts\")  as value FROM \"nuodb_statements\" WHERE (\"host\"::tag =~ /^$host$/) AND $timeFilter GROUP BY \"id\"::tag fill(null))",
       "select": [
        [
         { "params": [ "numexecutes" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / 30" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Updates",
     "type": "piechart",
     "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_id",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "id::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nuodb_statements",
       "query": "select top(\"value\",10) as value, id from (SELECT sum(\"updates\")  as value FROM \"nuodb_statements\" WHERE (\"host\"::tag =~ /^$host$/) AND $timeFilter GROUP BY \"id\"::tag fill(null))",
       "select": [
        [
         { "params": [ "numexecutes" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / 30" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Deletes",
     "type": "piechart",
     "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_id",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "id::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nuodb_statements",
       "query": "select top(\"value\",10) as value, id from (SELECT mean(\"deletions\")  as value FROM \"nuodb_statements\" WHERE (\"host\"::tag =~ /^$host$/) AND $timeFilter GROUP BY \"id\"::tag fill(null))",
       "select": [
        [
         { "params": [ "numexecutes" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / 30" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Replaces",
     "type": "piechart",
     "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_id",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "id::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nuodb_statements",
       "query": "select top(\"value\",10) as value, id from (SELECT mean(\"replaces\")  as value FROM \"nuodb_statements\" WHERE (\"host\"::tag =~ /^$host$/) AND $timeFilter GROUP BY \"id\"::tag fill(null))",
       "select": [
        [
         { "params": [ "numexecutes" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / 30" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Record Fetched",
     "type": "piechart",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_id",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "id::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nuodb_statements",
       "query": "select top(\"value\",10) as value, id from (SELECT mean(\"recordsfetched\")  as value FROM \"nuodb_statements\" WHERE (\"host\"::tag =~ /^$host$/) AND $timeFilter GROUP BY \"id\"::tag fill(null))",
       "select": [
        [
         { "params": [ "numexecutes" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / 30" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "type": "table",
     "gridPos": { "h": 20, "w": 18, "x": 3, "y": 6 },
     "targets": [
      {
       "measurement": "nuodb_statements",
       "query": "select \"id\",\"sqlstring\" FROM (SELECT \"id\",\"sqlstring\",last(\"exectime\") FROM \"nuodb_statements\" WHERE $timeFilter GROUP BY \"id\", \"sqlstring\")",
       "select": [
        [
         { "params": [ "exectime" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "IndexHits",
     "type": "piechart",
     "gridPos": { "h": 5, "w": 3, "x": 21, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_id",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "id::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nuodb_statements",
       "query": "select top(\"value\",10) as value, id from (SELECT mean(\"indexhits\")  as value FROM \"nuodb_statements\" WHERE (\"host\"::tag =~ /^$host$/)  AND $timeFilter GROUP BY \"id\"::tag fill(null))",
       "select": [
        [
         { "params": [ "numexecutes" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / 30" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Record Locked",
     "type": "piechart",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_id",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "id::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nuodb_statements",
       "query": "select top(\"value\",10) as value, id from (SELECT mean(\"locked\")  as value FROM \"nuodb_statements\" WHERE (\"host\"::tag =~ /^$host$/) AND $timeFilter GROUP BY \"id\"::tag fill(null))",
       "select": [
        [
         { "params": [ "numexecutes" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / 30" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "RejectedIndexHits",
     "type": "piechart",
     "gridPos": { "h": 5, "w": 3, "x": 21, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_id",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "id::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nuodb_statements",
       "query": "select top(\"value\",10) as value, id from (SELECT mean(\"rejectedhits\")  as value FROM \"nuodb_statements\" WHERE (\"host\"::tag =~ /^$host$/) AND $timeFilter GROUP BY \"id\"::tag fill(null))",
       "select": [
        [
         { "params": [ "numexecutes" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / 30" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Record Sorted",
     "type": "piechart",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_id",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "id::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nuodb_statements",
       "query": "select top(\"value\",10) as value, id from (SELECT mean(\"sorted\")  as value FROM \"nuodb_statements\" WHERE (\"host\"::tag =~ /^$host$/) AND $timeFilter GROUP BY \"id\"::tag fill(null))",
       "select": [
        [
         { "params": [ "numexecutes" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / 30" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "IndexFetches",
     "type": "piechart",
     "gridPos": { "h": 5, "w": 3, "x": 21, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_id",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "id::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nuodb_statements",
       "query": "select top(\"value\",10) as value, id from (SELECT mean(\"indexfetches\")  as value FROM \"nuodb_statements\" WHERE (\"host\"::tag =~ /^$host$/) AND $timeFilter GROUP BY \"id\"::tag fill(null))",
       "select": [
        [
         { "params": [ "numexecutes" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / 30" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Record Evicted",
     "type": "piechart",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_id",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "id::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nuodb_statements",
       "query": "select top(\"value\",10) as value, id from (SELECT mean(\"evicted\")  as value FROM \"nuodb_statements\" WHERE (\"host\"::tag =~ /^$host$/) AND $timeFilter GROUP BY \"id\"::tag fill(null))",
       "select": [
        [
         { "params": [ "numexecutes" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / 30" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "TableFetches",
     "type": "piechart",
     "gridPos": { "h": 5, "w": 3, "x": 21, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_id",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "id::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nuodb_statements",
       "query": "select top(\"value\",10) as value, id from (SELECT mean(\"tablefetches\")  as value FROM \"nuodb_statements\" WHERE (\"host\"::tag =~ /^$host$/) AND $timeFilter GROUP BY \"id\"::tag fill(null))",
       "select": [
        [
         { "params": [ "numexecutes" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / 30" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "Selected SQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "type": "table",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "sqlstring::tag" ], "type": "tag" }
     ],
     "measurement": "nuodb_statements",
     "select": [
      [
       { "params": [ "numexecutes" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ],
     "tags": [
      { "key": "id::tag", "operator": "=~", "value": "/^$id$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Exec Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "alias": "exectime",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nuodb_statements",
     "query": "SELECT sum(a) FROM (SELECT mean(\"rate\") as a FROM \"SqlStatementExecTime\" WHERE (\"db\" =~ /^$database$/) AND (\"host\" =~ /^$host$/)  AND $timeFilter GROUP BY startid, time($__interval) fill(null)) group BY time($__interval)",
     "select": [
      [
       { "params": [ "exectime" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / $collection" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Execution Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "exectime",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nuodb_statements",
     "query": "SELECT sum(a) FROM (SELECT mean(\"rate\") as a FROM \"SqlStatementExecTime\" WHERE (\"db\" =~ /^$database$/) AND (\"host\" =~ /^$host$/)  AND $timeFilter GROUP BY startid, time($__interval) fill(null)) group BY time($__interval)",
     "select": [
      [
       { "params": [ "exectime" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / $collection" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "id::tag", "operator": "=~", "value": "/^$id$/" }
     ]
    }
   ]
  },
  {
   "title": "Compile Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "compiletime",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nuodb_statements",
     "query": "SELECT sum(a) FROM (SELECT mean(\"rate\") as a FROM \"SqlStatementExecTime\" WHERE (\"db\" =~ /^$database$/) AND (\"host\" =~ /^$host$/)  AND $timeFilter GROUP BY startid, time($__interval) fill(null)) group BY time($__interval)",
     "select": [
      [
       { "params": [ "compiletime" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / $collection" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "id::tag", "operator": "=~", "value": "/^$id$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Number Executes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "numexecutes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nuodb_statements",
     "query": "SELECT sum(a) FROM (SELECT mean(\"rate\") as a FROM \"SqlStatementExecTime\" WHERE (\"db\" =~ /^$database$/) AND (\"host\" =~ /^$host$/)  AND $timeFilter GROUP BY startid, time($__interval) fill(null)) group BY time($__interval)",
     "select": [
      [
       { "params": [ "numexecutes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / $collection" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Num Executed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "value",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nuodb_statements",
     "query": "SELECT sum(a) FROM (SELECT mean(\"rate\") as a FROM \"SqlStatementExecTime\" WHERE (\"db\" =~ /^$database$/) AND (\"host\" =~ /^$host$/)  AND $timeFilter GROUP BY startid, time($__interval) fill(null)) group BY time($__interval)",
     "select": [
      [
       { "params": [ "numexecutes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / $collection" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "id::tag", "operator": "=~", "value": "/^$id$/" }
     ]
    }
   ]
  },
  {
   "title": "SQL Rows ",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Selects",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nuodb_statements",
     "query": "SELECT sum(a) FROM (SELECT mean(\"rate\") as a FROM \"SqlStatementExecTime\" WHERE (\"db\" =~ /^$database$/) AND (\"host\" =~ /^$host$/)  AND $timeFilter GROUP BY startid, time($__interval) fill(null)) group BY time($__interval)",
     "select": [
      [
       { "params": [ "recordsreturned" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / $collection" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "id::tag", "operator": "=~", "value": "/^$id$/" }
     ]
    },
    {
     "alias": "Inserts",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nuodb_statements",
     "query": "SELECT sum(a) FROM (SELECT mean(\"rate\") as a FROM \"SqlStatementExecTime\" WHERE (\"db\" =~ /^$database$/) AND (\"host\" =~ /^$host$/)  AND $timeFilter GROUP BY startid, time($__interval) fill(null)) group BY time($__interval)",
     "select": [
      [
       { "params": [ "inserts" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / $collection" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "id::tag", "operator": "=~", "value": "/^$id$/" }
     ]
    },
    {
     "alias": "Updates",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nuodb_statements",
     "query": "SELECT sum(a) FROM (SELECT mean(\"rate\") as a FROM \"SqlStatementExecTime\" WHERE (\"db\" =~ /^$database$/) AND (\"host\" =~ /^$host$/)  AND $timeFilter GROUP BY startid, time($__interval) fill(null)) group BY time($__interval)",
     "select": [
      [
       { "params": [ "updates" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / $collection" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "id::tag", "operator": "=~", "value": "/^$id$/" }
     ]
    },
    {
     "alias": "Deletes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nuodb_statements",
     "query": "SELECT sum(a) FROM (SELECT mean(\"rate\") as a FROM \"SqlStatementExecTime\" WHERE (\"db\" =~ /^$database$/) AND (\"host\" =~ /^$host$/)  AND $timeFilter GROUP BY startid, time($__interval) fill(null)) group BY time($__interval)",
     "select": [
      [
       { "params": [ "deletions" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / $collection" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "id::tag", "operator": "=~", "value": "/^$id$/" }
     ]
    }
   ]
  },
  {
   "title": "Index Hits",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "indexhits",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nuodb_statements",
     "query": "SELECT sum(a) FROM (SELECT mean(\"rate\") as a FROM \"SqlStatementExecTime\" WHERE (\"db\" =~ /^$database$/) AND (\"host\" =~ /^$host$/)  AND $timeFilter GROUP BY startid, time($__interval) fill(null)) group BY time($__interval)",
     "select": [
      [
       { "params": [ "indexhits" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / $collection" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "id::tag", "operator": "=~", "value": "/^$id$/" }
     ]
    }
   ]
  },
  {
   "title": "Rejected Index Hits",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "rejectedindexhits",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nuodb_statements",
     "query": "SELECT sum(a) FROM (SELECT mean(\"rate\") as a FROM \"SqlStatementExecTime\" WHERE (\"db\" =~ /^$database$/) AND (\"host\" =~ /^$host$/)  AND $timeFilter GROUP BY startid, time($__interval) fill(null)) group BY time($__interval)",
     "select": [
      [
       { "params": [ "rejectedindexhits" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / $collection" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "id::tag", "operator": "=~", "value": "/^$id$/" }
     ]
    }
   ]
  },
  {
   "title": "Index Scan Fetches",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "indexfetches",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nuodb_statements",
     "query": "SELECT sum(a) FROM (SELECT mean(\"rate\") as a FROM \"SqlStatementExecTime\" WHERE (\"db\" =~ /^$database$/) AND (\"host\" =~ /^$host$/)  AND $timeFilter GROUP BY startid, time($__interval) fill(null)) group BY time($__interval)",
     "select": [
      [
       { "params": [ "indexfetches" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / $collection" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "id::tag", "operator": "=~", "value": "/^$id$/" }
     ]
    }
   ]
  },
  {
   "title": "Table Scan Fetches",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "exhautivefetches",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nuodb_statements",
     "query": "SELECT sum(a) FROM (SELECT mean(\"rate\") as a FROM \"SqlStatementExecTime\" WHERE (\"db\" =~ /^$database$/) AND (\"host\" =~ /^$host$/)  AND $timeFilter GROUP BY startid, time($__interval) fill(null)) group BY time($__interval)",
     "select": [
      [
       { "params": [ "exhaustivefetches" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / $collection" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "id::tag", "operator": "=~", "value": "/^$id$/" }
     ]
    }
   ]
  },
  {
   "title": "# Index Scans",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "indexbatchfetches",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nuodb_statements",
     "query": "SELECT sum(a) FROM (SELECT mean(\"rate\") as a FROM \"SqlStatementExecTime\" WHERE (\"db\" =~ /^$database$/) AND (\"host\" =~ /^$host$/)  AND $timeFilter GROUP BY startid, time($__interval) fill(null)) group BY time($__interval)",
     "select": [
      [
       { "params": [ "indexbatchfetches" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / $collection" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "id::tag", "operator": "=~", "value": "/^$id$/" }
     ]
    }
   ]
  },
  {
   "title": "# Table Scans",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "exhautivebatchfetches",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nuodb_statements",
     "query": "SELECT sum(a) FROM (SELECT mean(\"rate\") as a FROM \"SqlStatementExecTime\" WHERE (\"db\" =~ /^$database$/) AND (\"host\" =~ /^$host$/)  AND $timeFilter GROUP BY startid, time($__interval) fill(null)) group BY time($__interval)",
     "select": [
      [
       { "params": [ "exhaustivebatchfetches" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / $collection" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "id::tag", "operator": "=~", "value": "/^$id$/" }
     ]
    }
   ]
  },
  {
   "title": "Records Fetched",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "recordsfetched",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nuodb_statements",
     "query": "SELECT sum(a) FROM (SELECT mean(\"rate\") as a FROM \"SqlStatementExecTime\" WHERE (\"db\" =~ /^$database$/) AND (\"host\" =~ /^$host$/)  AND $timeFilter GROUP BY startid, time($__interval) fill(null)) group BY time($__interval)",
     "select": [
      [
       { "params": [ "recordsfetched" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / $collection" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "id::tag", "operator": "=~", "value": "/^$id$/" }
     ]
    }
   ]
  },
  {
   "title": "Records Locked",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "locked",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nuodb_statements",
     "query": "SELECT sum(a) FROM (SELECT mean(\"rate\") as a FROM \"SqlStatementExecTime\" WHERE (\"db\" =~ /^$database$/) AND (\"host\" =~ /^$host$/)  AND $timeFilter GROUP BY startid, time($__interval) fill(null)) group BY time($__interval)",
     "select": [
      [
       { "params": [ "locked" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / $collection" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "id::tag", "operator": "=~", "value": "/^$id$/" }
     ]
    }
   ]
  },
  {
   "title": "Records Sorted",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "recordssorted",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nuodb_statements",
     "query": "SELECT sum(a) FROM (SELECT mean(\"rate\") as a FROM \"SqlStatementExecTime\" WHERE (\"db\" =~ /^$database$/) AND (\"host\" =~ /^$host$/)  AND $timeFilter GROUP BY startid, time($__interval) fill(null)) group BY time($__interval)",
     "select": [
      [
       { "params": [ "recordssorted" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / $collection" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "id::tag", "operator": "=~", "value": "/^$id$/" }
     ]
    }
   ]
  },
  {
   "title": "Records Evicted",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "recordsevicted",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nuodb_statements",
     "query": "SELECT sum(a) FROM (SELECT mean(\"rate\") as a FROM \"SqlStatementExecTime\" WHERE (\"db\" =~ /^$database$/) AND (\"host\" =~ /^$host$/)  AND $timeFilter GROUP BY startid, time($__interval) fill(null)) group BY time($__interval)",
     "select": [
      [
       { "params": [ "evicted" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / $collection" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "id::tag", "operator": "=~", "value": "/^$id$/" }
     ]
    }
   ]
  }
 ]
}