{
 "title": "SQL Log",
 "time": { "from": "2023-07-27T20:17:00.000Z", "to": "2023-07-27T20:27:00.000Z" },
 "templating": {
  "list": [
   { "name": "statement", "label": "statement", "query": ".+" },
   { "name": "explainplan", "label": "explainplan", "query": ".+" },
   { "name": "search", "label": "search" },
   { "name": "filters" }
  ]
 },
 "panels": [
  {
   "title": "New Panel",
   "type": "table",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "body": "select sqlstring,ID from system.localstatementcache",
     "fields": [
      { "jsonPath": "$.data[*].sql", "language": "jsonpath" },
      { "jsonPath": "$.data[*].statement", "language": "jsonpath", "name": "" }
     ],
     "method": "GET",
     "params": [
      [
       "dbname",
       "$database"
      ]
     ],
     "urlPath": "/query"
    }
   ]
  },
  {
   "title": "Statement Distribution",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 5, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(statement) (count_over_time({source=\"executions\", explainplan=~\"$explainplan\", statement=~\"$statement\"} [$__range]))"
    }
   ]
  },
  {
   "title": "Explain Plan Distribution",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 5, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk by(explainplan) (20, sum by(explainplan) (count_over_time({source=\"executions\", explainplan=~\"$explainplan\", statement=\"$statement\"} [$__range])))"
    }
   ]
  },
  {
   "title": "Top 10 ExecTime for first 5000 execution in time window",
   "type": "piechart",
   "description": "Note the calculation is down in browser and the query is limited to 5000 lines returned from loki.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{job=\"execution\", stmthash=~\"$statement\"} |~ `$filter` |= `$xplan` | logfmt",
     "maxLines": 5000,
     "resolution": 1
    }
   ]
  },
  {
   "title": "New Panel",
   "type": "logs",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{job=\"execution\", stmthash=~\"$statement\"} |~ `$filter` |= `$xplan` | logfmt"
    }
   ]
  }
 ]
}