{
 "title": "SQL Logs",
 "description": "NuoDB Summary",
 "tags": [
  "sql",
  "overview"
 ],
 "time": { "from": "2023-07-29T04:05:47.002Z", "to": "2023-07-29T04:11:18.190Z" },
 "templating": {
  "list": [
   { "name": "loginterval", "label": "interval" },
   {
    "name": "interval",
    "label": "interval",
    "query": "10s,30s,1m,5m,10m,15m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "database",
    "label": "Database",
    "query": "select distinct(\"db\") from (select first(raw) from \"Milliseconds\" where $timeFilter GROUP BY \"db\")\n"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "select distinct(\"host\") from (select first(raw) from \"Milliseconds\" where $timeFilter AND db =~ /$database$/ AND nodetype = 'Transaction' GROUP BY \"host\")\n"
   },
   { "name": "statement", "label": "statement", "query": ".+" },
   { "name": "execution", "label": "execution", "query": ".+" },
   { "name": "filter", "label": "filter" },
   { "name": "query", "label": "query" }
  ]
 },
 "panels": [
  {
   "title": "Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Summary",
   "type": "graph",
   "description": "The left y-axis is for the stack bar graph that shows relative (in terms of cores) breakdown of where processing time is being spent.  The right y-axis and grey shadow area graph is an indication of the total number of cores available by all selected TEs.",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "measurement relative to vCPU" }
   ],
   "targets": [
    {
     "alias": "$measurement",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(nthreads) as \"nthreads\" FROM (SELECT mean(raw) / 10000. as \"nthreads\" FROM \"Summary.Fetch\",\"Summary.Commit\",\"Summary.Sync\",\"Summary.Lock\",\"Summary.NtwkSend\",\"Summary.Throttle\",\"Summary.CPU\" WHERE $timeFilter AND nodetype = 'Transaction' AND host =~ /^$host$/ AND db =~ /^$database$/ GROUP BY time($__interval), \"pid\" fill(null)) GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$measurement",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "NumberCores",
     "query": "SELECT sum(ncores) FROM (SELECT mean(\"raw\") as ncores FROM \"NumberCores\" WHERE (\"db\" =~ /^$database$/ AND \"host\" =~ /^$host$/ AND \"nodetype\" = 'Transaction') AND $timeFilter GROUP BY time($__interval), \"startid\" fill(null)) GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "raw" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "db", "operator": "=~", "value": "/^$database$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "nodetype", "operator": "=", "value": "Transaction" }
     ]
    }
   ]
  },
  { "title": "Log", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "type": "table",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "body": "select sqlstring from system.localstatementcache where ID='$statement'",
     "fields": [
      { "jsonPath": "$.rows[*][0]", "name": "sqlstring" }
     ],
     "method": "POST",
     "params": [
      [
       "dbname",
       "$database"
      ],
      [
       "hostname",
       "localhost"
      ]
     ],
     "urlPath": "/query"
    }
   ]
  },
  {
   "title": "Log Counts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(source) (count_over_time({source=\"executions\", statement=~\"$statement\", explainplan=~\"$execution\", db=\"$database\", hostname=~\"$host\"} |~ `$filter` | logfmt [$__interval]))"
    }
   ]
  },
  {
   "title": "Statement Execution Logs",
   "type": "logs",
   "description": "Output is limited to 2000 lines",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "{source=\"executions\", statement=~\"$statement\", explainplan=~\"$execution\", db=\"$database\", hostname=~\"$host\"} |~ `$filter` | logfmt",
     "maxLines": 2000
    }
   ]
  }
 ]
}