{
 "title": "SQL Execution Logs",
 "description": "Log of each statement execution",
 "tags": [
  "sql",
  "overview"
 ],
 "time": { "from": "2023-07-29T04:05:47.002Z", "to": "2023-07-29T04:11:18.190Z" },
 "templating": {
  "list": [
   { "name": "loginterval", "label": "loginterval" },
   {
    "name": "interval",
    "label": "interval",
    "query": "10s,30s,1m,5m,10m,15m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "database",
    "label": "Database",
    "query": "select distinct(\"db\") from (select first(raw) from \"Milliseconds\" where $timeFilter GROUP BY \"db\")\n"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "select distinct(\"host\") from (select first(raw) from \"Milliseconds\" where $timeFilter AND db =~ /$database$/ AND nodetype = 'Transaction' GROUP BY \"host\")\n"
   },
   { "name": "statement", "label": "statement", "query": "undefined" },
   { "name": "execution", "label": "execution", "query": ".+" },
   { "name": "filter" },
   { "name": "query", "label": "query" }
  ]
 },
 "panels": [
  {
   "title": "Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "SQL Execute Time - ${__interval} interval",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "alias": "ExecTime",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nuodb_statements",
     "query": "SELECT max(avgexectime) FROM \"nuodb_statements\" WHERE (\"db_name\"::tag =~ /^$database$/ AND \"host\"::tag =~ /^$host$/) AND \"id\"::tag =~ /^$statement$/ AND  $timeFilter GROUP BY time($__interval),sqlstring fill(0) ",
     "select": [
      [
       { "params": [ "exectime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "db_name::tag", "operator": "=~", "value": "/^$database$/" },
      { "condition": "AND", "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  { "title": "Log", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Statement Execution Counts",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by(source) (count_over_time({source=\"executions\", statement=~\"$statement\", explainplan=~\"$execution\", db=\"$database\", hostname=~\"$host\"} |~ `$filter` | logfmt [$__interval]))"
    }
   ]
  },
  {
   "title": "Statement Execution Logs",
   "type": "logs",
   "description": "Output is limited to 2000 lines",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{source=\"executions\", statement=~\"$statement\", explainplan=~\"$execution\", db=\"$database\", hostname=~\"$host\"} |~ `$filter` | logfmt",
     "maxLines": 2000
    }
   ]
  }
 ]
}