{
 "title": "SQL Overview",
 "tags": [ "overview" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "10s,30s,1m,5m,10m,15m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "database",
    "label": "database",
    "query": "SHOW TAG VALUES FROM \"Milliseconds\" WITH KEY = \"db\""
   },
   {
    "name": "host",
    "label": "host",
    "query": "select distinct(\"host\") from (select first(raw) from \"Milliseconds\" where $timeFilter AND db =~ /$database$/ AND nodetype = 'Transaction' GROUP BY \"host\")"
   }
  ]
 },
 "panels": [
  {
   "title": "Monitor Event Queue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Duration",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "alias": "Full",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "SqlClientExecute",
       "query": "SELECT SUM(R) FROM (SELECT mean(\"rate\") AS R FROM \"SqlMonitorFullTime\" WHERE (\"nodetype\" = 'Transaction' AND \"db\" =~ /^$database$/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) , startid fill(null)) GROUP BY time($__interval)",
       "select": [
        [
         { "params": [ "rate" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "nodetype", "operator": "=", "value": "Transaction" },
        { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
       ]
      },
      {
       "alias": "Empty",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "SqlClientConnectionTime",
       "query": "SELECT SUM(R) FROM (SELECT mean(\"rate\") AS R FROM \"SqlMonitorEmptyTime\" WHERE (\"nodetype\" = 'Transaction' AND \"db\" =~ /^$database$/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) , startid fill(null)) GROUP BY time($__interval)",
       "select": [
        [
         { "params": [ "rate" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "nodetype", "operator": "=", "value": "Transaction" },
        { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
       ]
      }
     ]
    },
    {
     "title": "Count",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "Full",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "SqlClientExecute",
       "query": "SELECT SUM(R) FROM (SELECT mean(\"rate\") AS R FROM \"SqlMonitorFull\" WHERE (\"nodetype\" = 'Transaction' AND \"db\" =~ /^$database$/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) , startid fill(null)) GROUP BY time($__interval)",
       "select": [
        [
         { "params": [ "rate" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "nodetype", "operator": "=", "value": "Transaction" },
        { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
       ]
      },
      {
       "alias": "Empty",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "SqlClientConnectionTime",
       "query": "SELECT SUM(R) FROM (SELECT mean(\"rate\") AS R FROM \"SqlMonitorEmpty\" WHERE (\"nodetype\" = 'Transaction' AND \"db\" =~ /^$database$/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) , startid fill(null)) GROUP BY time($__interval)",
       "select": [
        [
         { "params": [ "rate" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "nodetype", "operator": "=", "value": "Transaction" },
        { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Client Messages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "alias": "Execute",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlClientExecute",
     "query": "SELECT SUM(R) FROM (SELECT mean(\"rate\") AS R FROM \"SqlClientExecuteTime\" WHERE (\"nodetype\" = 'Transaction' AND \"db\" =~ /^$database$/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) , startid fill(null)) GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    },
    {
     "alias": "Prepare",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlClientConnectionTime",
     "query": "SELECT SUM(R) FROM (SELECT mean(\"rate\") AS R FROM \"SqlClientPrepareTime\" WHERE (\"nodetype\" = 'Transaction' AND \"db\" =~ /^$database$/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) , startid fill(null)) GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    },
    {
     "alias": "PrepareAndExecute",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlClientConnectionTime",
     "query": "SELECT SUM(R) FROM (SELECT mean(\"rate\") AS R FROM \"SqlClientPrepareExecuteTime\" WHERE (\"nodetype\" = 'Transaction' AND \"db\" =~ /^$database$/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) , startid fill(null)) GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    },
    {
     "alias": "ResultSet",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlClientConnectionTime",
     "query": "SELECT SUM(R) FROM (SELECT mean(\"rate\") AS R FROM \"SqlClientResultSetTime\" WHERE (\"nodetype\" = 'Transaction' AND \"db\" =~ /^$database$/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) , startid fill(null)) GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    },
    {
     "alias": "Transaction",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlClientConnectionTime",
     "query": "SELECT SUM(R) FROM (SELECT mean(\"rate\") AS R FROM \"SqlClientTransactionTime\" WHERE (\"nodetype\" = 'Transaction' AND \"db\" =~ /^$database$/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) , startid fill(null)) GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    },
    {
     "alias": "Connection",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlClientConnectionTime",
     "query": "SELECT SUM(R) FROM (SELECT mean(\"rate\") AS R FROM \"SqlClientConnectionTime\" WHERE (\"nodetype\" = 'Transaction' AND \"db\" =~ /^$database$/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) , startid fill(null)) GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    },
    {
     "alias": "Database",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlClientConnectionTime",
     "query": "SELECT SUM(R) FROM (SELECT mean(\"rate\") AS R FROM \"SqlClientDatabaseTime\" WHERE (\"nodetype\" = 'Transaction' AND \"db\" =~ /^$database$/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) , startid fill(null)) GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    }
   ]
  },
  {
   "title": "Duration",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Execute",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlClientExecute",
     "query": "SELECT SUM(R) FROM (SELECT mean(\"rate\") AS R FROM \"SqlClientExecuteTime\" WHERE (\"nodetype\" = 'Transaction' AND \"db\" =~ /^$database$/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) , startid fill(null)) GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    },
    {
     "alias": "Prepare",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlClientConnectionTime",
     "query": "SELECT SUM(R) FROM (SELECT mean(\"rate\") AS R FROM \"SqlClientPrepareTime\" WHERE (\"nodetype\" = 'Transaction' AND \"db\" =~ /^$database$/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) , startid fill(null)) GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    },
    {
     "alias": "PrepareAndExecute",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlClientConnectionTime",
     "query": "SELECT SUM(R) FROM (SELECT mean(\"rate\") AS R FROM \"SqlClientPrepareExecuteTime\" WHERE (\"nodetype\" = 'Transaction' AND \"db\" =~ /^$database$/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) , startid fill(null)) GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    },
    {
     "alias": "ResultSet",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlClientConnectionTime",
     "query": "SELECT SUM(R) FROM (SELECT mean(\"rate\") AS R FROM \"SqlClientResultSetTime\" WHERE (\"nodetype\" = 'Transaction' AND \"db\" =~ /^$database$/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) , startid fill(null)) GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    },
    {
     "alias": "Transaction",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlClientConnectionTime",
     "query": "SELECT SUM(R) FROM (SELECT mean(\"rate\") AS R FROM \"SqlClientTransactionTime\" WHERE (\"nodetype\" = 'Transaction' AND \"db\" =~ /^$database$/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) , startid fill(null)) GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    },
    {
     "alias": "Connection",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlClientConnectionTime",
     "query": "SELECT SUM(R) FROM (SELECT mean(\"rate\") AS R FROM \"SqlClientConnectionTime\" WHERE (\"nodetype\" = 'Transaction' AND \"db\" =~ /^$database$/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) , startid fill(null)) GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    },
    {
     "alias": "Database",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlClientConnectionTime",
     "query": "SELECT SUM(R) FROM (SELECT mean(\"rate\") AS R FROM \"SqlClientDatabaseTime\" WHERE (\"nodetype\" = 'Transaction' AND \"db\" =~ /^$database$/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) , startid fill(null)) GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    }
   ]
  },
  {
   "title": "Counts",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Execute",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlClientExecute",
     "query": "SELECT sum(\"rate\") AS R FROM \"SqlClientExecute\" WHERE (\"nodetype\" = 'Transaction' AND \"db\" =~ /^$database$/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time(10s) , start_id fill(null)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    },
    {
     "alias": "Prepare",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlClientConnectionTime",
     "query": "SELECT sum(\"rate\") FROM \"SqlClientPrepare\" WHERE (\"nodetype\" = 'Transaction' AND \"db\" =~ /^$database$/  AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    },
    {
     "alias": "PrepareAndExecute",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlClientConnectionTime",
     "query": "SELECT sum(\"rate\") FROM \"SqlClientPrepareExecute\" WHERE (\"nodetype\" = 'Transaction' AND \"db\" =~ /^$database$/  AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    },
    {
     "alias": "ResultSet",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlClientConnectionTime",
     "query": "SELECT sum(\"rate\") FROM \"SqlClientResultSet\" WHERE (\"nodetype\" = 'Transaction' AND \"db\" =~ /^$database$/  AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    },
    {
     "alias": "Transaction",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlClientConnectionTime",
     "query": "SELECT sum(\"rate\") FROM \"SqlClientTransaction\" WHERE (\"nodetype\" = 'Transaction' AND \"db\" =~ /^$database$/  AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    },
    {
     "alias": "Connection",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlClientConnectionTime",
     "query": "SELECT sum(\"rate\") FROM \"SqlClientConnection\" WHERE (\"nodetype\" = 'Transaction' AND \"db\" =~ /^$database$/  AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    },
    {
     "alias": "Database",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlClientConnectionTime",
     "query": "SELECT sum(\"rate\") FROM \"SqlClientDatabase\" WHERE (\"nodetype\" = 'Transaction' AND \"db\" =~ /^$database$/  AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    }
   ]
  },
  {
   "title": "Counts",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Execute",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlClientExecute",
     "query": "SELECT sum(\"rate\") AS R FROM \"SqlClientExecute\" WHERE (\"nodetype\" = 'Transaction' AND \"db\" =~ /^$database$/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time(10s) , start_id fill(null)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    },
    {
     "alias": "Prepare",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlClientConnectionTime",
     "query": "SELECT sum(\"rate\") FROM \"SqlClientPrepare\" WHERE (\"nodetype\" = 'Transaction' AND \"db\" =~ /^$database$/  AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    },
    {
     "alias": "PrepareAndExecute",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlClientConnectionTime",
     "query": "SELECT sum(\"rate\") FROM \"SqlClientPrepareExecute\" WHERE (\"nodetype\" = 'Transaction' AND \"db\" =~ /^$database$/  AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    },
    {
     "alias": "ResultSet",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlClientConnectionTime",
     "query": "SELECT sum(\"rate\") FROM \"SqlClientResultSet\" WHERE (\"nodetype\" = 'Transaction' AND \"db\" =~ /^$database$/  AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    },
    {
     "alias": "Transaction",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlClientConnectionTime",
     "query": "SELECT sum(\"rate\") FROM \"SqlClientTransaction\" WHERE (\"nodetype\" = 'Transaction' AND \"db\" =~ /^$database$/  AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    },
    {
     "alias": "Connection",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlClientConnectionTime",
     "query": "SELECT sum(\"rate\") FROM \"SqlClientConnection\" WHERE (\"nodetype\" = 'Transaction' AND \"db\" =~ /^$database$/  AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    },
    {
     "alias": "Database",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlClientConnectionTime",
     "query": "SELECT sum(\"rate\") FROM \"SqlClientDatabase\" WHERE (\"nodetype\" = 'Transaction' AND \"db\" =~ /^$database$/  AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    }
   ]
  },
  {
   "title": "Platform",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Statement Exec Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlStatementExecTime",
     "query": "SELECT sum(a) FROM (SELECT mean(\"rate\") as a FROM \"SqlStatementExecTime\" WHERE (\"nodetype\" = 'Transaction')  AND (\"db\" =~ /^$database$/) AND (\"host\" =~ /^$host$/)  AND $timeFilter GROUP BY startid, time($__interval) fill(null)) group BY time($__interval)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" }
     ]
    }
   ]
  },
  {
   "title": "Statement Compile Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlStatementExecTime",
     "query": "SELECT sum(a) FROM (SELECT mean(\"rate\") as a FROM \"SqlStatementCompileTime\" WHERE (\"nodetype\" = 'Transaction')  AND (\"db\" =~ /^$database$/) AND (\"host\" =~ /^$host$/)  AND $timeFilter GROUP BY startid, time($__interval) fill(null)) group BY time($__interval)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" }
     ]
    }
   ]
  },
  {
   "title": "Idle Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlListenerIdleTime",
     "query": "SELECT SUM(R) FROM (SELECT mean(\"value\") AS R FROM \"SqlListenerIdleTime\" WHERE (\"nodetype\" = 'Transaction' AND \"db\" =~ /^$database$/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY startid, time($__interval) fill(null)) GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" }
     ]
    }
   ]
  },
  {
   "title": "Proc Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlListenerSqlProcTime",
     "query": "SELECT SUM(R) FROM (SELECT mean(\"value\") AS R FROM \"SqlListenerSqlProcTime\" WHERE (\"nodetype\" = 'Transaction' AND \"db\" =~ /^$database$/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY startid, time($__interval) fill(null)) GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Commits",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlListenerSqlProcTime",
     "query": "SELECT SUM(R) FROM (SELECT mean(\"rate\") AS R FROM \"Commits\" WHERE (\"nodetype\" = 'Transaction' AND \"db\" =~ /^$database$/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY startid, time($__interval) fill(null)) GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Inserts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Inserts",
     "query": "SELECT sum(a) FROM (SELECT mean(\"rate\") as a FROM \"Inserts\" WHERE  (\"nodetype\" = 'Transaction' AND \"db\" =~ /^$database$/ AND \"host\" =~ /^$host$/)   AND $timeFilter GROUP BY startid, time($__interval) fill(null)) group BY time($__interval)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" }
     ]
    }
   ]
  },
  {
   "title": "Updates",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Updates",
     "query": "SELECT sum(a) FROM (SELECT mean(\"rate\") as a FROM \"Updates\" WHERE (\"nodetype\" = 'Transaction')  AND (\"db\" =~ /^$database$/) AND (\"host\" =~ /^$host$/)  AND $timeFilter GROUP BY startid, time($__interval) fill(null)) group BY time($__interval)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" }
     ]
    }
   ]
  },
  {
   "title": "Deletes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Deletes",
     "query": "SELECT sum(a) FROM (SELECT mean(\"rate\") as a FROM \"Deletes\" WHERE (\"nodetype\" = 'Transaction' AND \"db\" =~ /^$database$/ AND \"host\" =~ /^$host$/)  AND $timeFilter GROUP BY startid, time($__interval) fill(null)) group BY time($__interval)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" }
     ]
    }
   ]
  },
  {
   "title": "Rows",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Statements Executed",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 13 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlStatementCount",
     "query": "SELECT sum(a) FROM (SELECT mean(\"rate\") as a FROM \"SqlStatementCount\" WHERE (\"nodetype\" = 'Transaction')  AND (\"db\" =~ /^$database$/) AND (\"host\" =~ /^$host$/)  AND $timeFilter GROUP BY startid, time($__interval) fill(null)) group BY time($__interval)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" }
     ]
    }
   ]
  },
  {
   "title": "Statements Executed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlStatementCount",
     "query": "SELECT sum(a) FROM (SELECT mean(\"rate\") as a FROM \"SqlStatementCount\" WHERE (\"nodetype\" = 'Transaction')  AND (\"db\" =~ /^$database$/) AND (\"host\" =~ /^$host$/)  AND $timeFilter GROUP BY startid, time($__interval) fill(null)) group BY time($__interval)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" }
     ]
    }
   ]
  },
  {
   "title": "SQL",
   "type": "piechart",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Selects",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlStatementRecordsReturned",
     "query": "SELECT sum(a) FROM (SELECT mean(\"rate\") as a FROM \"SqlStatementRecordsReturned\" WHERE(\"nodetype\" = 'Transaction')  AND (\"db\" =~ /^$database$/) AND (\"host\" =~ /^$host$/)  AND $timeFilter GROUP BY startid, time($__interval) fill(null)) group BY time($__interval)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" }
     ]
    },
    {
     "alias": "Inserts",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlStatementInserts",
     "query": "SELECT sum(a) FROM (SELECT mean(\"rate\") as a FROM \"SqlStatementInserts\" WHERE (\"nodetype\" = 'Transaction')  AND (\"db\" =~ /^$database$/) AND (\"host\" =~ /^$host$/)  AND $timeFilter GROUP BY startid, time($__interval) fill(null)) group BY time($__interval)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" }
     ]
    },
    {
     "alias": "Updates",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlStatementUpdates",
     "query": "SELECT sum(a) FROM (SELECT mean(\"rate\") as a FROM \"SqlStatementUpdates\" WHERE (\"nodetype\" = 'Transaction')  AND (\"db\" =~ /^$database$/) AND (\"host\" =~ /^$host$/)  AND $timeFilter GROUP BY startid, time($__interval) fill(null)) group BY time($__interval)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" }
     ]
    },
    {
     "alias": "Replace",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlStatementReplaces",
     "query": "SELECT sum(a) FROM (SELECT mean(\"rate\") as a FROM \"SqlStatementReplaces\" WHERE(\"nodetype\" = 'Transaction')  AND (\"db\" =~ /^$database$/) AND (\"host\" =~ /^$host$/)  AND $timeFilter GROUP BY startid, time($__interval) fill(null)) group BY time($__interval)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" }
     ]
    },
    {
     "alias": "Deletes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlStatementDeletes",
     "query": "SELECT sum(a) FROM (SELECT mean(\"rate\") as a FROM \"SqlStatementDeletes\" WHERE (\"nodetype\" = 'Transaction')  AND (\"db\" =~ /^$database$/) AND (\"host\" =~ /^$host$/)  AND $timeFilter GROUP BY startid, time($__interval) fill(null)) group BY time($__interval)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" }
     ]
    }
   ]
  },
  {
   "title": "SQL Rows by Operation",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Selects",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlStatementRecordsReturned",
     "query": "SELECT sum(a) FROM (SELECT mean(\"rate\") as a FROM \"SqlStatementRecordsReturned\" WHERE(\"nodetype\" = 'Transaction')  AND (\"db\" =~ /^$database$/) AND (\"host\" =~ /^$host$/)  AND $timeFilter GROUP BY startid, time($__interval) fill(null)) group BY time($__interval)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" }
     ]
    },
    {
     "alias": "Inserts",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlStatementInserts",
     "query": "SELECT sum(a) FROM (SELECT mean(\"rate\") as a FROM \"SqlStatementInserts\" WHERE(\"nodetype\" = 'Transaction')  AND (\"db\" =~ /^$database$/) AND (\"host\" =~ /^$host$/)  AND $timeFilter GROUP BY startid, time($__interval) fill(null)) group BY time($__interval)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" }
     ]
    },
    {
     "alias": "Updates",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlStatementUpdates",
     "query": "SELECT sum(a) FROM (SELECT mean(\"rate\") as a FROM \"SqlStatementUpdates\" WHERE (\"nodetype\" = 'Transaction')  AND (\"db\" =~ /^$database$/) AND (\"host\" =~ /^$host$/)  AND $timeFilter GROUP BY startid, time($__interval) fill(null)) group BY time($__interval)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" }
     ]
    },
    {
     "alias": "Replace",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlStatementReplaces",
     "query": "SELECT sum(a) FROM (SELECT mean(\"rate\") as a FROM \"SqlStatementReplaces\" WHERE(\"nodetype\" = 'Transaction')  AND (\"db\" =~ /^$database$/) AND (\"host\" =~ /^$host$/)  AND $timeFilter GROUP BY startid, time($__interval) fill(null)) group BY time($__interval)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" }
     ]
    },
    {
     "alias": "Deletes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlStatementDeletes",
     "query": "SELECT sum(a) FROM (SELECT mean(\"rate\") as a FROM \"SqlStatementDeletes\" WHERE (\"nodetype\" = 'Transaction')  AND (\"db\" =~ /^$database$/) AND (\"host\" =~ /^$host$/)  AND $timeFilter GROUP BY startid, time($__interval) fill(null)) group BY time($__interval)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" }
     ]
    }
   ]
  },
  {
   "title": "Indexes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Index Hits",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlStatementIndexHits",
     "query": "SELECT sum(a) FROM (SELECT mean(\"rate\") as a FROM \"SqlStatementIndexHits\" WHERE(\"nodetype\" = 'Transaction')  AND (\"db\" =~ /^$database$/) AND (\"host\" =~ /^$host$/)  AND $timeFilter GROUP BY startid, time($__interval) fill(null)) group BY time($__interval)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" }
     ]
    }
   ]
  },
  {
   "title": "Rejected Index Hits",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlStatementRejectedIndexHits",
     "query": "SELECT sum(a) FROM (SELECT mean(\"rate\") as a FROM \"SqlStatementRejectedIndexHits\" WHERE (\"nodetype\" = 'Transaction')  AND (\"db\" =~ /^$database$/) AND (\"host\" =~ /^$host$/)  AND $timeFilter GROUP BY startid, time($__interval) fill(null)) group BY time($__interval)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" }
     ]
    }
   ]
  },
  {
   "title": "IndexScan Fetches",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlStatementIndexFetches",
     "query": "SELECT sum(a) FROM (SELECT mean(\"rate\") as a FROM \"SqlStatementIndexFetches\" WHERE(\"nodetype\" = 'Transaction')  AND (\"db\" =~ /^$database$/) AND (\"host\" =~ /^$host$/)  AND $timeFilter GROUP BY startid, time($__interval) fill(null)) group BY time($__interval)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" }
     ]
    }
   ]
  },
  {
   "title": "TableScan Fetches",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlStatementExhaustiveFetches",
     "query": "SELECT sum(a) FROM (SELECT mean(\"rate\") as a FROM \"SqlStatementExhaustiveFetches\" WHERE (\"nodetype\" = 'Transaction')  AND (\"db\" =~ /^$database$/) AND (\"host\" =~ /^$host$/)  AND $timeFilter GROUP BY startid, time($__interval) fill(null)) group BY time($__interval)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" }
     ]
    }
   ]
  },
  {
   "title": "# IndexScans",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlStatementIndexBatchFetches",
     "query": "SELECT sum(a) FROM (SELECT mean(\"rate\") as a FROM \"SqlStatementIndexBatchFetches\" WHERE(\"nodetype\" = 'Transaction')  AND (\"db\" =~ /^$database$/) AND (\"host\" =~ /^$host$/)  AND $timeFilter GROUP BY startid, time($__interval) fill(null)) group BY time($__interval)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" }
     ]
    }
   ]
  },
  {
   "title": "# TableScans",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlStatementExhaustiveBatchFetches",
     "query": "SELECT sum(a) FROM (SELECT mean(\"rate\") as a FROM \"SqlStatementExhaustiveBatchFetches\" WHERE (\"nodetype\" = 'Transaction')  AND (\"db\" =~ /^$database$/) AND (\"host\" =~ /^$host$/)  AND $timeFilter GROUP BY startid, time($__interval) fill(null)) group BY time($__interval)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" }
     ]
    }
   ]
  },
  {
   "title": "Records",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "repeat": "SQLStatementStats",
   "targets": [
    {}
   ]
  },
  {
   "title": "Records Fetched",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlStatementRecordsFetched",
     "query": "SELECT sum(a) FROM (SELECT mean(\"rate\") as a FROM \"SqlStatementRecordsFetched\" WHERE (\"nodetype\" = 'Transaction')  AND (\"db\" =~ /^$database$/) AND (\"host\" =~ /^$host$/)  AND $timeFilter GROUP BY startid, time($__interval) fill(null)) group BY time($__interval)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" }
     ]
    }
   ]
  },
  {
   "title": "Records Locked",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlStatementLockedRecords",
     "query": "SELECT sum(a) FROM (SELECT mean(\"rate\") as a FROM \"SqlStatementLockedRecords\" WHERE(\"nodetype\" = 'Transaction')  AND (\"db\" =~ /^$database$/) AND (\"host\" =~ /^$host$/)  AND $timeFilter GROUP BY startid, time($__interval) fill(null)) group BY time($__interval)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" }
     ]
    }
   ]
  },
  {
   "title": "Records Sorted",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlStatementRecordsSorted",
     "query": "SELECT sum(a) FROM (SELECT mean(\"rate\") as a FROM \"SqlStatementRecordsSorted\" WHERE (\"nodetype\" = 'Transaction')  AND (\"db\" =~ /^$database$/) AND (\"host\" =~ /^$host$/)  AND $timeFilter GROUP BY startid, time($__interval) fill(null)) group BY time($__interval)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" }
     ]
    }
   ]
  },
  {
   "title": "Records Evicted",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlStatementEvicted",
     "query": "SELECT sum(a) FROM (SELECT mean(\"rate\") as a FROM \"SqlStatementEvicted\" WHERE(\"nodetype\" = 'Transaction')  AND (\"db\" =~ /^$database$/) AND (\"host\" =~ /^$host$/)  AND $timeFilter GROUP BY startid, time($__interval) fill(null)) group BY time($__interval)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" }
     ]
    }
   ]
  }
 ]
}