{
 "title": "SQL Query Details",
 "description": "Log of each statement execution",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "10s,30s,1m,5m,10m,15m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "database",
    "label": "Database",
    "query": "select distinct(\"db\") from (select first(raw) from \"Milliseconds\" where $timeFilter GROUP BY \"db\")\n"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "select distinct(\"host\") from (select first(raw) from \"Milliseconds\" where $timeFilter AND db =~ /$database$/ AND nodetype = 'Transaction' GROUP BY \"host\")\n"
   },
   { "name": "statement", "label": "statement", "query": "S7719849790278110983" }
  ]
 },
 "panels": [
  {
   "title": "Query",
   "type": "table",
   "description": "The selected normalized query string",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "SELECT last(avgexectime) FROM \"nuodb_querymetrics\" WHERE (\"id\"::tag = '$statement') AND $timeFilter GROUP BY \"statement\"::tag, \"id\"::tag LIMIT 1"
    }
   ]
  },
  {
   "title": "Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Execution Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "alias": "$tag_host ( db: $tag_db_name, startid: $tag_start_id )",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nuodb_statements",
     "query": "SELECT max(avgexectime) FROM \"nuodb_querymetrics\" WHERE (\"db_name\"::tag =~ /^$database$/ AND \"host\"::tag =~ /^$host$/) AND \"id\"::tag =~ /^$statement$/ AND  $timeFilter GROUP BY time($__interval), db_name, start_id,host fill(0) ",
     "select": [
      [
       { "params": [ "exectime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "db_name::tag", "operator": "=~", "value": "/^$database$/" },
      { "condition": "AND", "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "max",
     "query": "SELECT max(maxexectime) FROM \"nuodb_querymetrics\" WHERE (\"db_name\"::tag =~ /^$database$/ AND \"host\"::tag =~ /^$host$/) AND \"id\"::tag =~ /^$statement$/ AND  $timeFilter GROUP BY time($__interval) fill(0) "
    },
    {
     "alias": "min",
     "query": "SELECT min(minexectime) FROM \"nuodb_querymetrics\" WHERE (\"db_name\"::tag =~ /^$database$/ AND \"host\"::tag =~ /^$host$/) AND \"id\"::tag =~ /^$statement$/ AND  $timeFilter GROUP BY time($__interval) fill(0) "
    }
   ]
  },
  {
   "title": "Compile Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "alias": "$tag_host ( db: $tag_db_name, startid: $tag_start_id )",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nuodb_statements",
     "query": "SELECT max(avgcompiletime) FROM \"nuodb_querymetrics\" WHERE (\"db_name\"::tag =~ /^$database$/ AND \"host\"::tag =~ /^$host$/) AND \"id\"::tag =~ /^$statement$/ AND  $timeFilter GROUP BY time($__interval), start_id, host, db_name fill(0) ",
     "select": [
      [
       { "params": [ "exectime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "db_name::tag", "operator": "=~", "value": "/^$database$/" },
      { "condition": "AND", "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "max",
     "query": "SELECT max(maxcompiletime) FROM \"nuodb_querymetrics\" WHERE (\"db_name\"::tag =~ /^$database$/ AND \"host\"::tag =~ /^$host$/) AND \"id\"::tag =~ /^$statement$/ AND  $timeFilter GROUP BY time($__interval) fill(0) "
    },
    {
     "alias": "min",
     "query": "SELECT min(mincompiletime) FROM \"nuodb_querymetrics\" WHERE (\"db_name\"::tag =~ /^$database$/ AND \"host\"::tag =~ /^$host$/) AND \"id\"::tag =~ /^$statement$/ AND  $timeFilter GROUP BY time($__interval) fill(0) "
    }
   ]
  },
  {
   "title": "Executions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "[$tag_start_id] $tag_host ($tag_db_name)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nuodb_statements",
     "query": "SELECT max(count) FROM \"nuodb_querymetrics\" WHERE (\"db_name\"::tag =~ /^$database$/ AND \"host\"::tag =~ /^$host$/) AND \"id\"::tag =~ /^$statement$/ AND  $timeFilter GROUP BY time($__interval), start_id,host fill(0) ",
     "select": [
      [
       { "params": [ "exectime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "db_name::tag", "operator": "=~", "value": "/^$database$/" },
      { "condition": "AND", "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Records Fetched",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nuodb_statements",
     "query": "SELECT max(recordsfetchedatmaxtime) FROM \"nuodb_querymetrics\" WHERE (\"db_name\"::tag =~ /^$database$/ AND \"host\"::tag =~ /^$host$/) AND \"id\"::tag =~ /^$statement$/ AND  $timeFilter GROUP BY time($__interval) fill(0) ",
     "select": [
      [
       { "params": [ "exectime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "db_name::tag", "operator": "=~", "value": "/^$database$/" },
      { "condition": "AND", "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "min",
     "query": "SELECT min(recordsfetchedatmintime) FROM \"nuodb_querymetrics\" WHERE (\"db_name\"::tag =~ /^$database$/ AND \"host\"::tag =~ /^$host$/) AND \"id\"::tag =~ /^$statement$/ AND  $timeFilter GROUP BY time($__interval) fill(0) "
    }
   ]
  },
  { "title": "Log", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Statement Execution Logs",
   "type": "logs",
   "description": "Output is limited to 2000 lines",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "{statement=~\"$statement\", db=\"$database\", hostname=~\"$host\"} |~ `$filter` | logfmt",
     "maxLines": 2000
    }
   ]
  }
 ]
}