{{ $namespace := include "insights.namespace" $ }}
{{- if ne $namespace "!" -}}
{{- range $key, $val := .Values.insights.grafana.datasources }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-datasource-{{ $key | replace "_" "." | lower }}
  namespace: {{ $namespace }}
  labels:
    {{ $.Values.grafana.sidecar.datasources.label | default "grafana_datasource" }}: "nuodb"
    {{- include "insights.labels" $ | nindent 4 }}
data:
  {{ $key }}.yaml: |-
    apiVersion: 1
    datasources:
      - name: '{{ get $val "database" }}'
        type: influxdb
        access: proxy
        orgId: 1
        url: {{ include "insights.influxdb_url" $ }}
        password: ''
        user: ''
        basicAuth: false
        basicAuthUser: ''
        basicAuthPassword: ''
        withCredentials: false
        isDefault: {{ and (hasKey $val "isDefault") (get $val "isDefault") }}
        jsonData:
          timeInterval: '{{ get $val "timeInterval" }}'
          dbName: '{{ get $val "database" }}'
          httpMode: GET
          httpHeaderName1: 'Authorization'
        secureJsonData: 
          httpHeaderValue1: 'Token {{ include "insights.influxdb_token" $ }}'
        version: 1
        editable: true
{{ end }}
{{- end }}
