---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nuoca.fullname" . }}-configmap
  labels:
    {{- include "nuoca.labels" . | nindent 4 }}
data: 
  nuoca.yml.template: |-
    NUOCA_LOGFILE: /var/log/nuodb/nuoca.log
    INPUT_PLUGINS:
{{- if .Values.nuoadmin }}
    - NuoAdminNuoMon:
        description : Collection from NuoDB engines (nuoadmin)
        nuocaCollectionName: NuoMon
        api_server: ${NUOCMD_API_SERVER}
{{- if and .Values.nuoadmin.tls .Values.nuoadmin.tls.enabled }}
        client_key: ${NUOCMD_CLIENT_KEY}
{{- end }}
        host_uuid_shortname: True
{{- end }}
{{- if .Values.nuoagent }}
    - NuoMon:
        description : Collection from internal nuomonitor tool
        broker: ${DOMAIN_BROKER}
        domain_username: ${DOMAIN_USER}
        domain_password: ${DOMAIN_PASSWORD}
        database_regex_pattern: '^(?!nuodb_system|\\.).*'
        host_uuid_shortname: True
{{- end }}
    OUTPUT_PLUGINS:
    - InfluxDB:
        url: ${INFLUXDB_URL}


  
